#!/usr/bin/env bash
# mise description="Run code formatting"
# mise sources=["**/*.swift"]

OUTPUT_DIR="build/lint/reports"
mkdir -p "${OUTPUT_DIR}"

swiftlint --fix --strict --quiet --reporter html --output "${OUTPUT_DIR}/swiftlint.html"
swiftformat . --report "${OUTPUT_DIR}/swiftformat.json"
