name: Swift

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/cache@v3
      name: 'Cache .build folder'
      with:
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-

    - name: Setup Swift
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: "5.6"

    - name: Build
      run: swift build -v

    - name: Run tests
      run: swift test -v
