name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/cache@v3
      name: 'Cache .build folder'
      with:
        path: .build
        key: ${{ runner.os }}-spm-v1-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-v1-

    - name: Build
      run: swift build -v

    - name: Run tests
      run: swift test -v

  lint:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3

    - uses: jdx/mise-action@v2
      with:
        experimental: true
    
    - name: Lint
      run: mise r format

    - uses: actions/upload-artifact@v3
      with:
        name: lint-build-reports
        path: .build/reports
