name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/cache@v3
      name: 'Cache .build folder'
      with:
        path: .build
        key: ${{ runner.os }}-spm-v1-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-v1-

    - name: Build
      run: swift build -v

    - name: Run tests
      run: swift test -v

  lint:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Tuist
      run: |
        bash <(curl -Ls https://install.tuist.io)
    
    - name: Tuist fetch
      run: |
        tuist fetch
    
    - name: SwiftFormat
      run: |
        mkdir -p .build/reports
        tuist swiftformat lint --report .build/reports/swiftformat.json

    - uses: actions/upload-artifact@v3
      with:
        name: lint-build-reports
        path: .build/reports
